#ifndef DEFINE_HPP
#define DEFINE_HPP

// REPLY
#define RPL_WELCOME "001"
#define RPL_NAMREPLY "353"
#define RPL_ENDOFNAMES "366"




// ERROR
#define ERR_UNKNOWNCOMMAND "421"
#define ERR_ERRONEUSNICKNAME "432" 
#define ERR_NICKNAMEINUSE "433"
#define ERR_NOTREGISTERED "451"
#define ERR_NEEDMOREPARAMS "461"
#define ERR_ALREADYREGISTRED "462"
#define ERR_PASSWDMISMATCH "464"


#endif